name: PreRelease

on:
  push:
    branches:
      - dev
      - web

  workflow_dispatch:

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare environment
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.x"

      - name: Install Pyinstaller and Nuitka
        run: pip install --upgrade wheel pyinstaller nuitka zstandard orderedset imageio

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Install Playwright Browsers
        env:
          PLAYWRIGHT_BROWSERS_PATH: "0"
        run: playwright install chromium

      - name: Build Pyinstaller Binary
        run: pyinstaller main.spec

      - name: Build Nuitka Binary
        run: nuitka --onefile --standalone --show-progress --output-dir=nuitka --windows-icon-from-ico=tv.png --user-package-configuration-file=nuitka.yml .\main.py

      - name: Get commit hash
        id: commit
        uses: pr-mpt/actions-commit-hash@v2

      - name: Rename Binary
        run: |
          mv ./dist/$(python release.py --buildname) ./build/$(python release.py --name --package-tools pyinstaller --beta {{ steps.commit.outputs.hash }})
          mv ./nuitka/$(python release.py --buildname) ./build/$(python release.py --name --package-tools nuitka --beta {{ steps.commit.outputs.hash }})

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: v$(python release.py --version --beta {{ steps.commit.outputs.hash }})
          files: build/*
